### PR TITLE
chore: use poetry and the black formatter

### PR DESCRIPTION
**Pull request by ooliver1**
This PR moves and edits `pyproject.toml` to be the dependency management. This also edits pre-commit and dev-dependencies to use [black](https://github.com/psf/black).

### CODE REVIEW

**Comment by Numerlor** [comment]
do we need black in poetry deps if it's handled in the pre-commit? Same for flake8 and isort

**Comment by ooliver1** [comment]
> do we need black in poetry deps if it's handled in the pre-commit? Same for flake8 and isort

Means they are installed for editors to use, such as `flake8` editor hints, and `Format Document` in editors (format on save too).

**Comment by c-gaskell** [comment]
> do we need black in poetry deps if it's handled in the pre-commit? Same for flake8 and isort

the pre-commit requirements only handle the pre-commits environment afaik, to use them in your IDE and such you would need to install them with poetry. that's how i've always used it at least

**Comment by Numerlor** [comment]
pre-commit can be run with `pre-commit ruin --all-files` to get the linting done all at once as expected, though if there's some IDE integration that isn't there with pure pre-commit it's fine to leave

**Comment by c-gaskell** [comment]
Does poetry.lock need to be added to the gitignore?

**Comment by Numerlor** [comment]
the lock file should be tracked to get reproducible environments from poetry

**Comment by ooliver1** [comment]
> Does poetry.lock need to be added to the gitignore?

Usually people do that for libraries where the lock file is never used, what Numerlor said is why lock files are useful.

**Comment by c-gaskell** [comment]
Ah ok, i thought lock files were usually local. I thought poetry itself handles making sure everything is reproducible?

**Comment by ooliver1** [comment]
The lock file locks all dependencies to an exact version, instead of any direct dependency that matches the version.

**Comment by c-gaskell** [comment]
Ah ok, got it. I'm happy to merge then

**Review by c-gaskell — APPROVED** [review]

**Pull request merged**
